version: '3.5'
services:
  db:
    image: mongo:latest
    restart: always
    container_name: SBTrip-mongodb
    environment:
      - MONGO_DATA_DIR=/db/data
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --logpath=/dev/null

  web:
    build: .
    links:
      - db
    container_name: SBTrip-Server
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MONGODB_PORT=27017
      - MONGODB_SCHEMA=sbt
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db